<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Brander\Page\Block\SocialLinks $block */
?>
<ul>
    <?php foreach($this->getSocialLinks() as $key => $link): ?>
        <?php $image = $this->getImagePath($link['image']); ?>
        <?php if($image): ?>
            <li>
                <a href="<?= $this->getSocialUrl($link['url']); ?>">
                    <img width="30px"  height="30px" src="<?= $this->getImagePath($link['image']); ?>" alt="<?= $link['label'] ?>" />
                </a>
            </li>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>
